### ISSUE TITLE
Error when using `crop` option.

### ISSUE THREAD

**Issue by SnidelyWhiplash** [achingbrain/mongoose-crate-imagemagick#1]
Thanks for the great set of modules, they've been working pretty painlessly for me thus far. However, I'm running into an issue when trying to use the `crop` option.

``` js
Schema.plugin(crate, {
  storage: new S3(app.conf.s3),
  fields: {
    images: {
      array: true,
      processor: new ImageMagick({
        transforms: {
          cropped: {
            crop: '125x125'
          }
        }
      })
    }
  }
});
```

```
[Error: Command failed: identify: unable to open image `/var/folders/p7/p1pdn4_x26vd4211zg_mjczc0000gn/T/5cb7f65cddb54d612014.': No such file or directory @ error/blob.c/OpenBlob/2645.
identify: no decode delegate for this image format `/var/folders/p7/p1pdn4_x26vd4211zg_mjczc0000gn/T/5cb7f65cddb54d612014.' @ error/constitute.c/ReadImage/501.]
```

I've been able to use `resize` without any problems. Any ideas?

**Comment by achingbrain** [comment]
Hmm, that's weird - it looks like the stored file has no extension, maybe that's throwing off identify?

**Comment by achingbrain** [comment]
Ignore my previous reply.

The problem is you need to specify x and y offsets to the crop command, otherwise you end up tiling the image - see http://www.imagemagick.org/script/command-line-options.php#crop for more.

In short, use `crop: '125x125-0-0'` instead.

**Comment by SnidelyWhiplash** [comment]
Ahhhhhh, yeah I see now, thanks a ton it's working perfectly now. :)

On a somewhat unrelated note, I noticed this lib is using [rsms/node-imagemagick](https://github.com/rsms/node-imagemagick). The README there says it's abandoned and suggests using the fork at [yourdeveloper/node-imagemagick](https://github.com/yourdeveloper/node-imagemagick). But both actually suggest using [aheckmann/gm](https://github.com/aheckmann/gm) instead. Any chance of that happening? If you have an interest, I'll open up a new issue and perhaps submit a PR if I find the time.

Thanks again for your help, and the lib itself, it's working perfectly for my needs thus far!

**Comment by SnidelyWhiplash** [comment]
Also, in regards to the missing extension, that was just an oversight in my implementation. Unrelated, but has since been fixed as well. Thanks for pointing it out. :)

**Comment by SnidelyWhiplash** [comment]
Closing this.
